name: example-environment
channels:
  - conda-forge
  - pytorch
  - ipnyb
dependencies:
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - pytorch
  - torchvision
  - six
  - pydotplus
  - seaborn
  - mlrose
  - ipnyb
